### ISSUE TITLE
Input pattern also matches directories

### ISSUE THREAD

**Issue by m99coder** [Siilwyn/mustache-prestatic#24]
I’m using the following command:

```bash
$ ./node_modules/.bin/mustache-prestatic ./views/**/* --partials ./partials/**/* --output ./public --verbose
templateFiles [
  './views/directory',
  './views/directory/file.html'
]
data undefined
partials [
  './partials/directory',
  './partials/directory/partial.mustache'
]
```

It results in the following errors:

```
(node:23168) UnhandledPromiseRejectionWarning: Error: EISDIR: illegal operation on a directory, read
(node:23168) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
(node:23168) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

My assumption is that the specified directory is read, but not limited to files.

**Comment by Siilwyn** [comment]
Thank you for the detailed issue @m99coder!

Your assumption is correct, the directory is read like it is a file: https://github.com/Siilwyn/mustache-prestatic/blob/36185f1abbeb436953fcb6c13cf14a650680ab7b/src/index.js#L46

As a workaround you could use the JS interface or narrow down the glob to mustache files with `./views/**/*.mustache`.

I have added a test that is skipped for now but should pass when fixing this issue: https://github.com/Siilwyn/mustache-prestatic/blob/aa00a4c6b187f62174f7d397f41e45a0d9d4a0bf/tests/test.js#L66-L70

In the foreseeable future I won't have time to fix this issue unfortunately but a PR is more than welcome and will be published asap.

**Comment by m99coder** [comment]
Hi Selwyn,

I had a deeper look at the issue. If I’m not mistaken the interface of `mapTemplates` already requires resolved file paths. My gut feeling is that the `transform` method in `/bin/mustache-prestatic.js` should resolve glob patterns to file lists before calling the actual API. What do you think?

**Comment by Siilwyn** [comment]
Alright, I modified the readme and handle invalid files with a explicit error.
